# Generated by Django 4.0.2 on 2023-02-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='git',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
